name = "speke-website"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "speke-waitlist"
database_id = "c1cd6b67-ba71-4cdc-9bdb-2318896e3573"
preview_database_id = "c1cd6b67-ba71-4cdc-9bdb-2318896e3573"
